"""Extract the existing browser rules without bundling its embedded credentials."""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    html = (ROOT / "MiniMax-H3-提示词生成器.html").read_text(encoding="utf-8")
    main = next(s for s in re.findall(r"<script>(.*?)</script>", html, re.S)
                if "function i2vaAlignLine" in s)
    main = main.split("/* ==================== 初始化")[0]
    for name in ("_decodeKey", "_decodeKeyGlm"):
        main, count = re.subn(r"function " + name + r"\(\) \{.*?\n\}",
                             "function " + name + '() { return "server-managed"; }', main, flags=re.S)
        if count != 1:
            raise RuntimeError("Credential removal failed: " + name)
    defaults = {}
    for match in re.finditer(r'<(input|select|textarea|div|span|button|output)[^>]*\bid="([^"]+)"[^>]*>', html):
        value = re.search(r'value="([^"]*)"', match[0])
        defaults[match[2]] = {"value": value[1] if value else "", "checked": bool(re.search(r"\bchecked\b", match[0]))}
    output = ROOT / "prompt_engine"
    output.mkdir(exist_ok=True)
    (output / "rules.js").write_text("// Generated by scripts/build_prompt_engine.py; do not edit.\n" + main, encoding="utf-8")
    (output / "defaults.json").write_text(json.dumps(defaults, ensure_ascii=False), encoding="utf-8")
    (output / "source.sha256").write_text(hashlib.sha256(html.encode()).hexdigest() + "\n", encoding="ascii")


if __name__ == "__main__":
    build()
